import { DATA_ENTITIES as DE } from "./DataEntities.js";

/*
  Entidades de dados que são consumidas em cada ecrã
*/
export const ROUTE_DATA_DEPENDENCIES = {
  LOGIN_SCREEN_ROUTE: [
    DE.PEOPLE,
    DE.ACTUATOR_LOGS,
    DE.SENSOR_LOGS,
    DE.ENTRANCE_LOGS,
  ],
  PEOPLE_SCREEN_ROUTE: [DE.PEOPLE],
  PERMISSIONS_SCREEN_ROUTE: [DE.PERMISSIONS],
  ENTRANCES_SCREEN_ROUTE: [DE.ENTRANCE_LOGS],
  SENSOR_LOG_SCREEN_ROUTE: [DE.SENSOR_LOGS],
  ACTUATOR_LOG_SCREEN_ROUTE: [DE.ACTUATOR_LOGS],
  ENTRANCE_LOG_IMAGES_SCREEN_ROUTE: [DE.ENTRANCE_LOGS],
};
